# This is a basic workflow to help you get started with Actions
name: CI
on:
  push:
    branches: [ "gha-test" ]
  pull_request:
    branches: [ "gha-test" ]
jobs:
  Buildandpushdocker:
    runs-on: ubuntu-latest
    environment: Dev 
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: gitclone 
        run: git clone https://github.com/Shubhambawa98/testenv.git
      - name: docker installation 
        run: curl -fsSL https://get.docker.com | sh 
      - name: docker login 
        run: docker login -u ${{secrets.DOCKERHUBUSERNAME}} -p ${{secrets.DOCKERHUBPASSWORD}}
      - name: docker build 
        run: cd testenv && docker build . -t fast_api:satyam
      - name: test
        run: echo "hello"
      - name: docker tag & push  
        run: docker tag fast_api:satyam shubhambawa98/testlkm:satyam && docker push shubhambawa98/testlkm:satyam
